apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: componentA
  description: Something cool here.
  annotations:
    jfrog-artifactory/image-name: 0.1.0-alpha0194
spec:
  type: service
  lifecycle: production
  owner: example
